name: windows

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
      - name: Print IP Address
        run: ipconfig -all
      - name: Print Open IP Address
        run: curl http://ipinfo.io
      - name: Print System Information
        run: systeminfo
  
